### ISSUE TITLE
Provide helpful message at the first run when configurations are still empty

### ISSUE THREAD

**Issue by Pinolo** [sparkfabrik/sparktool#7] opened 2015-05-21 22:31 UTC
example output when configuration file is empty:

```
% ./spark.php redmine:search



  [Exception]
  <url> malformed



redmine:search [--report] [-l|--limit [LIMIT]] [-s|--sort [SORT]] [-p|--project_id [PROJECT_ID]] [--status [STATUS]] [--assigned [ASSIGNED]] [--sprint [SPRINT]] [--created [CREATED]] [--updated [UPDATED]] [--not-estimated] [--subject [SUBJECT]] [--tracker [TRACKER]]
```

**Comment by grota** [comment] 2015-05-22 14:47
Duplicate of #11

**Comment by grota** [comment] 2015-05-22 14:49
Fixed with #32

**Closed as completed** 2015-05-22 14:58 UTC
Labels: hackathon p1
